### ISSUE TITLE
CwpSearchBoostExtension assumes Metafields on RedirectorPage

### ISSUE THREAD

**Issue by phptek** [silverstripe/cwp-search#8]
Line 38 of `CwpSeaechBoostExtension.php` assumes all `Page` subclasses have metafields, but they are purposely removed in `RedirectorPage`.

**Comment by robbieaverill** [comment]
At a slightly higher level, should we be indexing redirector pages anyway?

**Comment by phptek** [comment]
No :-)

**Comment by scott1702** [comment]
Just ran into this, I feel that RedirectorPages which link to external sites should show in search. However when it comes RedirectorPages which link to internal pages I'm not sure. After a quick discussion with @clarkepaul we feel that it should be up to the CMS users to decide whether they should be shown. ie ensuring the CMS user is aware of the 'Show in Search' checkbox in the settings and when to use it for RedirectorPages. So an update to the userhelp docs would be beneficial here.

Either way, in the short term this bug should be fixed so that CwpSearchBoostExtension doesn't assume MetaData exists on all pages.

**Comment by clarkepaul** [comment]
We're adding some of these details to User Help as additional guidance for users.

**Comment by robbieaverill** [comment]
Fair enough justification!

**Comment by robbieaverill** [comment]
Fixed in #13

**Comment by ScopeyNZ** [comment]
Does this mean it should be closed now that's merged? I assume so - I'll close this. Reopen if I'm mistaken.
