### ISSUE TITLE
Support for Elemental content block module

### ISSUE THREAD

**Issue by madmatt** [silverstripe/cwp-search#9]
Are there any plans to include support for elemental in this module? While it's not officially part of the CWP core set of modules, it would be great to get optional support added in so that it just works (assuming you setup your index to include fields that should be included).

**Comment by robbieaverill** [comment]
Yep! So my understanding is that the elemental module has an example indexer which indexes elemental data in the context of its page (https://github.com/dnadesign/silverstripe-elemental/pull/158). The CWP indexer may need to include the same kind of logic if elemental is installed.

**Comment by madmatt** [comment]
Right - I had a quick skim of that code and as far as I can tell this only works if you publish the page that an element is added to, not if you publish the element itself, right?

This doesn't really work for the same reason that the previous version of search implementation in elemental didn't work, it relies on someone publishing an element, and then going back and publishing the page as well (which in SS4 potentially means pushing content from other elements that you weren't expecting live as well).

I would think the best solution would be to have it index `BaseElement` directly, but that would require changes to the search results template to aggregate page results (so the same page isn't included twice, so it's not an 'easy' solution).

**Comment by robbieaverill** [comment]
>Right - I had a quick skim of that code and as far as I can tell this only works if you publish the page that an element is added to, not if you publish the element itself, right?

Correct

>This doesn't really work for the same reason that the previous version of search implementation in elemental didn't work, it relies on someone publishing an element, and then going back and publishing the page as well (which in SS4 potentially means pushing content from other elements that you weren't expecting live as well).

We're trying to encourage users to publish pages and not content blocks by default (this is dev configurable of course). I know however that we still show the save/publish buttons for content blocks.

>I would think the best solution would be to have it index BaseElement directly

Yeah - the example I linked to earlier is designed to be a simple starter indexer that will index a page's elements under the page so search queries and results pages will still behave the same way. If you wanted to you could totally index the elements individually and modify the results page to handle this data structure too - you're right it's not as easy.

---

What's the expected outcome here? My expectation would be that the default CWP indexer should index content blocks under a page, as page data, in the same way the example elemental indexer does. Maybe we could add extra hooks to ensure that pages get reindexed when you publish a new content block under a page without having published the page as well (although this could be an anti-pattern, since I'd probably expect doing this to create a new version of the page, which would require a publish before propagating to the live site...)

**Comment by madmatt** [comment]
Yeah, maybe the better option here is to not have the publish button on an element, and instead tell people they need to publish at a page level instead?

However, that is quite a massive UI design / thought experiment switch just to have search work nicely, so I don't know what's better here. Perhaps @clarkepaul has some opinions/thoughts?

**Comment by clarkepaul** [comment]
We need the publish button on elements as there are times when people only want to publish a part of a page rather than the whole thing. As pages get more complex and there are more people collaborating on pages this becomes more of requirement—most people do publish on a page basis though and thats why we are hiding the publish button for individual blocks. 

Marking a page as a unique version makes sense even if a block is updated (even if the whole page hasn't been published), the page status would be "Modified" if it isn't all published. Blocks definitely need to be searchable but on a page basis.

**Comment by robbieaverill** [comment]
Just came across this again, it's a little confusing (even to me) when I have to opt in to indexing content blocks in CWP

**Comment by maxime-rainville** [comment]
Not relevant anymore.
